site_name: YT的个人网站
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - attr_list
  - pymdownx.tilde
  - markdown.extensions.attr_list
  - footnotes
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true  

extra_css:
  - styles/extra.css

nav:
  - 首页: index.md
  - 关于本网站和我:
      - 关于我: 个人信息.md
      - 关于网站: 为何做这个网站.md
  - 神秘试验田: exp/试验田.md
  - 学习:
      - 线性代数:
          - 线代期中复习记录: learn/线性代数/线代期中复习记录.md